// ═══ Deckstorm — hand-crafted pixel-art icon set (11px grids) ═══
// Chars map to PAL colors; "." = transparent. Every card type has a unique icon.
const PAL = {
  R: "#E23C50", P: "#FC84FC", G: "#FCE40C", B: "#5EC8F8", N: "#7CE6B2",
  W: "#F7F1E3", D: "#2B2B3A", V: "#8E5CF8", O: "#F29C50", S: "#9C93B8",
  K: "#171521", b: "#A0663C", C: "#7CE6E0",
};

const ICONS = {
  // ─── JOKERS ───
  joker: [
    "....G.G....",
    "...GG.GG...",
    "....G.G....",
    "..WWWWWWW..",
    "..WKWWWKW..",
    "..WWWWWWW..",
    "..WWWKWWW..",
    "..WRRRRRW..",
    "..WWWWWWW..",
  ],
  greedy: [
    ".....R.....",
    "....RRR....",
    "...RRRRR...",
    "..RRRRRRR..",
    ".RRRRRRRRR.",
    "RRRRRRRRRRR",
    ".RRRRRRRRR.",
    "..RRRRRRR..",
    "...RRRRR...",
    "....RRR....",
    ".....R.....",
  ],
  lusty: [
    "..RR...RR..",
    ".RRRR.RRRR.",
    "RRRRRRRRRRR",
    "RRRRRRRRRRR",
    "RRRRRRRRRRR",
    ".RRRRRRRRR.",
    "..RRRRRRR..",
    "...RRRRR...",
    "....RRR....",
    ".....R.....",
  ],
  wrathful: [
    ".....D.....",
    "....DDD....",
    "...DDDDD...",
    "..DDDDDDD..",
    ".DDDDDDDDD.",
    "DDDDDDDDDDD",
    "DDDDDDDDDDD",
    ".DD.DDD.DD.",
    ".....D.....",
    "....DDD....",
    "...DDDDD...",
  ],
  gluttonous: [
    "....NNN....",
    "...NNNNN...",
    "...NNNNN...",
    ".NNN.N.NNN.",
    "NNNNNNNNNNN",
    "NNNNNNNNNNN",
    ".NNNNNNNNN.",
    "..NN.N.NN..",
    ".....N.....",
    "....NNN....",
    "...NNNNN...",
  ],
  jolly: [
    ".G.......G.",
    ".PP.....PP.",
    ".PPP...PPP.",
    "..PPPPPPP..",
    "..PPPPPPP..",
    "..WWWWWWW..",
    "..WKWWWKW..",
    "..WWWWWWW..",
    "...WRRRW...",
  ],
  zany: [
    ".G.......G.",
    ".NN.....NN.",
    ".NNN...NNN.",
    "..NNNNNNN..",
    "..NNNNNNN..",
    "..WWWWWWW..",
    "..WKWWWKW..",
    "..WWWWWWW..",
    "...WRRRW...",
  ],
  mad: [
    ".R.......R.",
    ".GG.....GG.",
    ".GGG...GGG.",
    "..GGGGGGG..",
    "..GGGGGGG..",
    "..WWWWWWW..",
    "..WKWWWKW..",
    "..WWWWWWW..",
    "...WRRRW...",
  ],
  crazy: [
    ".N.......N.",
    ".BB.....BB.",
    ".BBB...BBB.",
    "..BBBBBBB..",
    "..BBBBBBB..",
    "..WWWWWWW..",
    "..WKWWWKW..",
    "..WWWWWWW..",
    "...WRRRW...",
  ],
  droll: [
    ".G.......G.",
    ".VV.....VV.",
    ".VVV...VVV.",
    "..VVVVVVV..",
    "..VVVVVVV..",
    "..WWWWWWW..",
    "..WKWWWKW..",
    "..WWWWWWW..",
    "...WRRRW...",
  ],
  sly: [
    "...BBBBB...",
    "..BWBBBWB..",
    ".BBBBBBBBB.",
    ".BWBWWWBWB.",
    ".BBBBBBBBB.",
    "..BWBBBWB..",
    "...BBBBB...",
  ],
  wily: [
    "...PPPPP...",
    "..PWPPPWP..",
    ".PPPPPPPPP.",
    ".PWPWWWPWP.",
    ".PPPPPPPPP.",
    "..PWPPPWP..",
    "...PPPPP...",
  ],
  clever: [
    "...GGGGG...",
    "..GWGGGWG..",
    ".GGGGGGGGG.",
    ".GWGWWWGWG.",
    ".GGGGGGGGG.",
    "..GWGGGWG..",
    "...GGGGG...",
  ],
  devious: [
    "...NNNNN...",
    "..NWNNNWN..",
    ".NNNNNNNNN.",
    ".NWNWWNWNN.",
    ".NNNNNNNNN.",
    "..NWNNNWN..",
    "...NNNNN...",
  ],
  crafty: [
    "...OOOOO...",
    "..OWOOOWO..",
    ".OOOOOOOOO.",
    ".OWOWWOWOO.",
    ".OOOOOOOOO.",
    "..OWOOOWO..",
    "...OOOOO...",
  ],
  half: [
    "..WWWWWDD..",
    "..WWWWWDD..",
    "..WWWWWDD..",
    "..WWWWWDD..",
    "..WWWWWDD..",
    "..WWWWWDD..",
    "..WWWWWDD..",
  ],
  banner: [
    ".DDDDDDDD..",
    ".DGGGGGGG..",
    ".DGGGGGGG..",
    ".DGGGGGGG..",
    ".DDDDDDDD..",
    ".D.........",
    ".D.........",
    ".D.........",
  ],
  misprint: [
    "...PPPP....",
    "..PP..PP...",
    "..BB...P...",
    "...B..PP...",
    "....PP.....",
    "....P......",
    "...........",
    "....P..B...",
  ],
  scholar: [
    "..DDDDDDDDD",
    "...DDDDDDD.",
    "....DDDDD..",
    "....D.G....",
    "....D.G....",
    "..WWWWWWW..",
    "..WWWWWWW..",
  ],
  business: [
    "...DDDDD...",
    "....DDD....",
    "....DDD....",
    "...DDDDD...",
    "..DDDDDDD..",
    "..DDDDDDD..",
    "...DDDDD...",
    "....DDD....",
  ],
  smiley: [
    "...WWWWW...",
    ".WWWWWWWWW.",
    ".WWKWWWKWW.",
    ".WWWWWWWWW.",
    ".WKWWWWWKW.",
    ".WWKKKKKWW.",
    "..WWWWWWW..",
    "...WWWWW...",
  ],
  green: [
    ".....N.....",
    "....NNN....",
    "...NNNNN...",
    "..NNNNNNN..",
    ".NNN.N.NNN.",
    ".....N.....",
    ".....N.....",
    "...NNNNN...",
  ],
  fortune: [
    "...VVVVV...",
    "..VWWVVWV..",
    ".VWWVVVVVV.",
    ".VWVVVVVVV.",
    "..VVVVVVV..",
    "...DDDDD...",
    "..DDDDDDD..",
  ],
  gros: [
    ".....D.....",
    "....GGG....",
    "...GGGGG...",
    "..GGG.GG...",
    "..GG...GG..",
    ".GG....GG..",
    ".GG...GGG..",
    "..GGGGGG...",
    "...GGGG....",
  ],
  icecream: [
    "...PPPPP...",
    "..PPPPPPP..",
    "..PPPPPPP..",
    "...bbbbb...",
    "....bbb....",
    "....bbb....",
    ".....b.....",
  ],
  egg: [
    "....WW.....",
    "...WWWW....",
    "..WWWWWW...",
    "..WWWWWW...",
    "..WWWWWW...",
    "...WWWW....",
    "....WW.....",
  ],
  blue: [
    ".B.......B.",
    ".BB.....BB.",
    ".BBB...BBB.",
    "..BBBBBBB..",
    "..BBBBBBB..",
    "..WWWWWWW..",
    "..WKWWWKW..",
    "..WWWWWWW..",
  ],
  bus: [
    ".OOOOOOOOOO",
    ".OKKOKKOKKO",
    ".OOOOOOOOOO",
    ".OOOOOOOOOO",
    ".OKKOOOOKKO",
  ],
  fibonacci: [
    "..GGGGGG...",
    "..G....G...",
    "..G.GG.G...",
    "..G.GG.G...",
    "..G....G...",
    "..GGGGGG...",
  ],
  even: [
    "..WWWWWWW..",
    "..WKWWWKW..",
    "..WWWWWWW..",
    "..WKWWWKW..",
    "..WWWWWWW..",
  ],
  odd: [
    "..WWWWWWW..",
    "..WKW.WKW..",
    "..WWWKWWW..",
    "..WKW.WKW..",
    "..WWWWWWW..",
  ],
  stencil: [
    "..SSSSSSS..",
    "..SSSKSSS..",
    "..SSKKKSS..",
    "..SSSKSSS..",
    "..SSSSSSS..",
  ],
  constellation: [
    ".B......B..",
    "...B..B....",
    "....BBB....",
    ".B..BBB..B.",
    "....BBB....",
    "...B..B....",
    ".B......B..",
  ],
  satellite: [
    ".BB.....BB.",
    ".BB..D..BB.",
    ".....DDD...",
    ".BB.DDD.BB.",
    ".BB..D..BB.",
    "......D....",
  ],
  cartomancer: [
    "..VVVVVVV..",
    "..V..K..V..",
    "..V.KKK.V..",
    "..V..K..V..",
    "..VVVVVVV..",
  ],
  burglar: [
    "...DDDDD...",
    "..DDDDDDD..",
    "..DKDDKDD..",
    "..DDDDDDD..",
    "...DDDDD...",
    "....bbb....",
  ],
  flowerpot: [
    "...P.P.P...",
    "....PPP....",
    "..N..P..N..",
    "...NNNNN...",
    "....bbb....",
    "...bbbbb...",
    "...bbbbb...",
  ],
  photograph: [
    "..WWWWWWW..",
    "..WBBBBBW..",
    "..WBKKKBW..",
    "..WBBBBBW..",
    "..WWWWWWW..",
  ],
  duo: [
    "..BBB.BBB..",
    ".BBBBBBBBB.",
    ".BBBBBBBBB.",
    "..BBB.BBB..",
  ],
  trio: [
    "..BB.BB.BB.",
    ".BBBBBBBBB.",
    "..BB.BB.BB.",
  ],
  family: [
    "..GG...GG..",
    "..GG...GG..",
    "...........",
    "..GG...GG..",
    "..GG...GG..",
  ],
  order: [
    ".........G.",
    ".......GGG.",
    ".....GGGGG.",
    "...GGGGGGG.",
    ".GGGGGGGGG.",
  ],
  tribe: [
    "..DDDDDDD..",
    ".DKDVDKDDD.",
    "..DDDDDDD..",
    "..DWWWWWD..",
    "...DDDDD...",
  ],

  // ─── PLANETS ───
  mercury: [
    "...SSSSS...",
    "..SbSbSSS..",
    ".SSSSbSSSS.",
    ".SbSSSSSSS.",
    ".SSSbSSSSS.",
    "..SSSSSSS..",
    "...SSSSS...",
  ],
  venus: [
    "...GGGGG...",
    "..GGGGGGG..",
    ".GGGGGGGGG.",
    ".GGGGGGGGG.",
    ".GGGGGGGGG.",
    "..GGGGGGG..",
    "...GGGGG...",
  ],
  earth: [
    "...BBBBB...",
    "..BBNNBBB..",
    ".BBNNNNBBB.",
    ".BBBBBNBBB.",
    ".BBNBBBBBB.",
    "..BBBBBBB..",
    "...BBBBB...",
  ],
  mars: [
    "...OOOOO...",
    "..OOROOOO..",
    ".OORROOOOO.",
    ".OOOOOOOOO.",
    ".OOOROOOOO.",
    "..OOOOOOO..",
    "...OOOOO...",
  ],
  jupiter: [
    "...OOOOO...",
    "..WWWWWWW..",
    ".OOOOOOOOO.",
    ".WWWWWWWWW.",
    ".ORROOOOOO.",
    "..WWWWWWW..",
    "...OOOOO...",
  ],
  saturn: [
    ".....GGG.....",
    "..GGGGGGGGG..",
    "GGGGGGGGGGGGG",
    "..GGGGGGGGG..",
    ".....GGG.....",
  ],
  uranus: [
    "....CCCCC..",
    "...CCCCCCC.",
    "CC.CCCCCCCC",
    "...CCCCCCC.",
    "....CCCCC..",
  ],
  neptune: [
    "...BBBBB...",
    "..BBVBBBB..",
    ".BBVBBBBBB.",
    ".BBBBBBBBB.",
    ".BBVBBBBBB.",
    "..BBBBBBB..",
    "...BBBBB...",
  ],
  pluto: [
    "....WWW....",
    "...WWWWW...",
    "...WWBWW...",
    "...WWWWW...",
    "....WWW....",
  ],
  planetx: [
    "...DDDDD...",
    "..DDDDDVV..",
    ".DDVDDDDDD.",
    ".DDDDDDVDD.",
    ".DDDDDDDDD.",
    "..DDDDDDD..",
    "...DDDDD...",
  ],
  ceres: [
    "...SSSSS...",
    "..SSKSSSS..",
    ".SSSSSKSSS.",
    ".SSSSSSSSS.",
    ".SKSSSSSSS.",
    "..SSSSSSS..",
    "...SSSSS...",
  ],
  eris: [
    "...PPPPP...",
    "..PPWPPPP..",
    ".PWWPPPPPP.",
    ".PPPPPPPPP.",
    ".PPWPPPPPP.",
    "..PPPPPPP..",
    "...PPPPP...",
  ],

  // ─── TAROTS ───
  fool: [
    "...G...G...",
    "..PPP.PPP..",
    "...PPPPP...",
    "....P.P....",
  ],
  magician: [
    "......G....",
    ".....GG....",
    "....GG.....",
    "...GG......",
    "..GG.......",
    "..W........",
  ],
  priestess: [
    "..D..W..D..",
    "..D.WW..D..",
    "..D..W..D..",
    "..D.WW..D..",
    "..D..W..D..",
  ],
  empress: [
    "..G.G.G.G..",
    "..GGGGGGG..",
    "...GGGGG...",
    "....R.R....",
    "....RRR....",
  ],
  emperor: [
    "..GGGGGGG..",
    "..G.....G..",
    "..G.GGG.G..",
    "..GGGGGGG..",
  ],
  hierophant: [
    "...G...G...",
    "...GG.GG...",
    "....G.G....",
    "...GG.GG...",
    "...G...G...",
  ],
  lovers: [
    "..RR...RR..",
    ".RRRR.RRRR.",
    ".RRRRRRRR..",
    "..RRRRRR...",
    "...RRRR....",
  ],
  chariot: [
    "....G.G....",
    "..G.GGG.G..",
    "..GGGGGGG..",
    "..G.GGG.G..",
    "....G.G....",
  ],
  justice: [
    ".....G.....",
    "..G..G..G..",
    ".GGG.G.GGG.",
    ".....G.....",
    "....GGG....",
  ],
  hermit: [
    "....GGG....",
    "...G...G...",
    "...G.W.G...",
    "...G...G...",
    "....GGG....",
  ],
  wheel: [
    "..GGGGGGG..",
    ".G..G.G..G.",
    ".G.GGGGG.G.",
    ".G..G.G..G.",
    "..GGGGGGG..",
  ],
  strength: [
    "..GGGGGGG..",
    ".GGOOOOOGG.",
    ".GOKOKOKGG.",
    ".GGOOOOOG..",
    "..GGGGGGG..",
  ],
  hanged: [
    ".....W.....",
    "....WWW....",
    "...W.W.W...",
    "....W.W....",
    "....W.W....",
  ],
  death: [
    "...WWWWW...",
    "..WWWWWWW..",
    "..WKWWWKW..",
    "..WWWWWWW..",
    "...WKWKW...",
  ],
  temperance: [
    "..BB...BB..",
    "..BB.BBBB..",
    "...BBBB....",
    "...B..B....",
    "..BBBBBB...",
  ],
  devil: [
    ".RR.....RR.",
    ".RRR...RRR.",
    "..RRRRRRR..",
    "..RKKKKKR..",
    "..RRRRRRR..",
  ],
  tower: [
    "...GGGGG...",
    "...G.G.G...",
    "...GGGGG...",
    "...GGGGG...",
    "...GGGGG...",
    "..GGGGGGG..",
  ],
  star: [
    ".....G.....",
    "....GGG....",
    ".GGGGGGGGG.",
    "..GGGGG....",
    "...GG.GG...",
    "..GG...GG..",
  ],
  moon: [
    "....WW.....",
    "...WW......",
    "..WW.......",
    "..WW.......",
    "...WW......",
    "....WW.....",
  ],
  sun: [
    ".G...G...G.",
    "..G.GGG.G..",
    "...GGGGG...",
    ".GGGGGGGGG.",
    "...GGGGG...",
    "..G.GGG.G..",
    ".G...G...G.",
  ],
  world: [
    "...BBBBB...",
    "..BNNBBNB..",
    ".BBNBNBBBB.",
    ".BBNNNBBBB.",
    "..BBBBBBB..",
    "...BBBBB...",
  ],
  judgement: [
    "..G........",
    "..GG.......",
    "..GGGGGGGG.",
    "..GG....GG.",
    "..G....GGG.",
  ],

  // ─── VOUCHERS ───
  overstock: [
    "..WW.WW.WW.",
    "..WWWWWWWW.",
    "..WW.WW.WW.",
  ],
  clearance: [
    "..GG....G..",
    ".G.GG..G...",
    "..GG..G....",
    ".G..GG.GG..",
  ],
  grabber: [
    "..W.W.W....",
    "..W.W.W.W..",
    "..WWWWW.W..",
    "...WWWWW...",
    "....WWW....",
  ],
  wasteful: [
    "....N.N....",
    "...N...N...",
    "..N.NNN....",
  ],
  seedmoney: [
    "....G.G....",
    "...GGGGG...",
    "..GG.G.GG..",
    "...GGGG....",
    "....G.G....",
  ],
  paintbrush: [
    "......bb...",
    ".....bb....",
    "....bb.....",
    "..Wbb......",
    ".WWW.......",
  ],
  hone: [
    "....VV.....",
    "...VVVV....",
    "..VVVVVV...",
    "...VVVV....",
    "....VV.....",
  ],

  // ─── PACKS ───
  buffoon: [
    "..PPPPPPP..",
    "..PG...GP..",
    "..PPPPPPP..",
  ],
  arcana: [
    "..GGGGGGG..",
    "..G..K..G..",
    "..GGGGGGG..",
  ],
  celestial: [
    "..BBBBBBB..",
    "..B.GGG.B..",
    "..BBBBBBB..",
  ],

  // ─── BOSSES ───
  hook: [
    "....DD.....",
    "...D..D....",
    "...D..D....",
    "......D....",
    "......D....",
    "..D...D....",
    "...DDD.....",
  ],
  water: [
    "....B......",
    "...BBB.....",
    "..BBBBB....",
    ".BBBBBBB...",
    ".BBBBBBB...",
    "..BBBBB....",
    "...BBB.....",
  ],
  needle: [
    ".....D.....",
    ".....D.....",
    ".....D.....",
    ".....D.....",
    "....DDD....",
    "....DDD....",
    "....D.D....",
  ],
  manacle: [
    "..DDD.DDD..",
    ".D...D...D.",
    ".D.DD.DD.D.",
    "..DDD.DDD..",
  ],
  wall: [
    ".SS.SSS.SS.",
    "SSS.SSS.SSS",
    ".SS.SSS.SS.",
    "SSS.SSS.SSS",
  ],
  club: [
    "....DDD....",
    "...DDDDD...",
    "...DDDDD...",
    ".DDD.D.DDD.",
    "DDDDDDDDDDD",
    "DDDDDDDDDDD",
    ".DDDDDDDDD.",
    "..DD.D.DD..",
    ".....D.....",
    "....DDD....",
  ],
  goad: [
    ".....D.....",
    "....DDD....",
    "...DDDDD...",
    "..DDDDDDD..",
    ".DDDDDDDDD.",
    "DDDDDDDDDDD",
    "DDDDDDDDDDD",
    ".DD.DDD.DD.",
    ".....D.....",
    "....DDD....",
  ],
  window: [
    ".....R.....",
    "....RRR....",
    "...RRRRR...",
    "..RRRRRRR..",
    ".RRRRRRRRR.",
    "RRRRRRRRRRR",
    ".RRRRRRRRR.",
    "..RRRRRRR..",
    "...RRRRR...",
    "....RRR....",
    ".....R.....",
  ],
  heart: [
    "..RR...RR..",
    ".RRRR.RRRR.",
    "RRRRRRRRRRR",
    "RRRRRRRRRRR",
    "RRRRRRRRRRR",
    ".RRRRRRRRR.",
    "..RRRRRRR..",
    "...RRRRR...",
    "....RRR....",
    ".....R.....",
  ],
  psychic: [
    "..DDDDDDD..",
    ".DWWWWWWWD.",
    ".DWWKKKWWD.",
    ".DWWWWWWWD.",
    "..DDDDDDD..",
  ],
};

function iconSVG(id) {
  const grid = ICONS[id];
  if (!grid) return "";
  const h = grid.length, w = grid[0].length;
  let rects = "";
  grid.forEach((row, y) => {
    for (let x = 0; x < row.length; x++) {
      const color = PAL[row[x]];
      if (color) rects += `<rect x='${x}' y='${y}' width='1' height='1' fill='${color}'/>`;
    }
  });
  return `<svg viewBox='0 0 ${w} ${h}' shape-rendering='crispEdges' aria-hidden='true'>${rects}</svg>`;
}
